import type { Language } from "../types";
const rows = {
  moreTools: ['More activities', 'Другие занятия', 'עוד פעילויות', 'أنشطة أخرى'],
  pickActivity: ['Pick an activity', 'Выбери занятие', 'בוחרים פעילות', 'اختر نشاطًا'],
  openActivity: ['Open', 'Открыть', 'פתיחה', 'افتح'],
  learningLanguage: ["Learning language", "Язык обучения", "שפת הלמידה", "لغة التعلم"],
  learningLanguageHelp: ["Notes, practice and tutor replies use this language. Your interface stays the same.", "Конспекты, задания и ответы наставника будут на этом языке. Язык интерфейса не изменится.", "הסיכומים, התרגול ותשובות המורה יהיו בשפה הזאת. שפת הממשק לא תשתנה.", "ستكون الملاحظات والتدريبات وردود المعلم بهذه اللغة. لن تتغير لغة الواجهة."],
  draftSaved: ["Draft saved in this tab. You can close this form or refresh.", "Черновик сохранён в этой вкладке. Можно закрыть форму или обновить страницу.", "הטיוטה נשמרה בלשונית הזאת. אפשר לסגור את הטופס או לרענן.", "حُفظت المسودة في هذا التبويب. يمكنك إغلاق النموذج أو تحديث الصفحة."],
  draftError: ["Draft autosave is unavailable. Copy your text before refreshing or closing this form.", "Не удалось сохранить черновик. Скопируйте текст перед обновлением или закрытием формы.", "השמירה האוטומטית אינה זמינה. העתיקו את הטקסט לפני רענון או סגירת הטופס.", "الحفظ التلقائي غير متاح. انسخ النص قبل التحديث أو إغلاق النموذج."],
  providerCredits: ["The AI provider has insufficient credits for this request. The app owner needs to check OpenRouter credits. Your topic is still here.", "У провайдера ИИ недостаточно средств для запроса. Владельцу приложения нужно проверить баланс OpenRouter. Тема сохранена здесь.", "אין לספק הבינה המלאכותית מספיק קרדיטים לבקשה. על בעלי האפליקציה לבדוק את יתרת OpenRouter. הנושא נשמר כאן.", "رصيد مزود الذكاء الاصطناعي غير كافٍ لهذا الطلب. على مالك التطبيق التحقق من رصيد OpenRouter. موضوعك لا يزال هنا."],
  invalidGeneration: ["The AI returned an incomplete or invalid study set. Your topic is saved here—please try again.", "ИИ вернул неполный или некорректный набор. Тема сохранена здесь — попробуйте ещё раз.", "הבינה המלאכותית החזירה ערכת לימוד לא תקינה או חלקית. הנושא נשמר כאן — נסו שוב.", "أعاد الذكاء الاصطناعي مجموعة غير مكتملة أو غير صالحة. موضوعك محفوظ هنا — حاول مرة أخرى."],
  independentDays: [
    "days with independent answers",
    "дней с самостоятельными ответами",
    "ימים עם תשובות עצמאיות",
    "أيام بإجابات مستقلة",
  ],
  today: ["Today", "Сегодня", "היום", "اليوم"],
  library: ["Library", "Библиотека", "ספרייה", "المكتبة"],
  practice: ["Practice", "Практика", "תרגול", "تدريب"],
  progress: ["Progress", "Прогресс", "התקדמות", "التقدم"],
  hello: [
    "What will you crack today?",
    "Что разберём сегодня?",
    "מה מפצחים היום?",
    "ماذا سنكتشف اليوم؟",
  ],
  welcome: [
    "One small win at a time.",
    "По одной маленькой победе.",
    "הצלחה קטנה בכל פעם.",
    "إنجاز صغير كل مرة.",
  ],
  promise: [
    "Pick a topic. Let’s crack it.",
    "Выбери тему. Разберёмся вместе.",
    "בוחרים נושא. מפצחים יחד.",
    "اختر موضوعًا. نفهمه معًا.",
  ],
  recommended: [
    "Picked for you",
    "Подобрано для тебя",
    "במיוחד בשבילך",
    "اخترناه لك",
  ],
  sprint: ["Study Sprint", "Учебный спринт", "סבב למידה", "جولة تعلم"],
  sprintDesc: [
    "A little learning, a little practice, a real “I get it.”",
    "Немного теории, немного практики — и «теперь понятно».",
    "קצת למידה, קצת תרגול, ורגע של ״הבנתי!״",
    "قليل من التعلم والتدريب، ولحظة «فهمت!»",
  ],
  start: ["Let’s learn", "Начать учиться", "בואו נלמד", "لنبدأ التعلم"],
  resume: [
    "Continue your sprint",
    "Продолжить спринт",
    "המשך סבב למידה",
    "تابع جولتك",
  ],
  minutes: [
    "min · at your pace",
    "мин · в своём темпе",
    "דק׳ · בקצב שלך",
    "دقائق · على مهلك",
  ],
  add: [
    "Add study material",
    "Добавить материал",
    "הוספת חומר לימוד",
    "أضف مادة دراسية",
  ],
  recent: [
    "Your recent discoveries",
    "Недавние открытия",
    "התגליות האחרונות שלך",
    "اكتشافاتك الأخيرة",
  ],
  empty: [
    "Your first topic goes here.",
    "Здесь будет твоя первая тема.",
    "כאן מתחילים עם נושא ראשון.",
    "موضوعك الأول يبدأ هنا.",
  ],
  all: ["See all", "Показать всё", "הצגת הכול", "عرض الكل"],
  source: ["Source", "Источник", "מקור", "المصدر"],
  topic: ["A topic", "Тема", "נושא", "موضوع"],
  text: ["Text", "Текст", "טקסט", "نص"],
  transcript: ["Transcript", "Транскрипт", "תמלול", "نص مفرغ"],
  file: ["PDF or photo", "PDF или фото", "PDF או תמונה", "PDF أو صورة"],
  title: ["Title", "Название", "כותרת", "العنوان"],
  input: [
    "What are we learning?",
    "Что будем изучать?",
    "מה לומדים?",
    "ماذا سنتعلم؟",
  ],
  sourceHelp: [
    "Paste the actual content. For video, paste its transcript; a URL alone is not enough.",
    "Вставь сам материал. Для видео нужен транскрипт, а не только ссылка.",
    "הדביקו את התוכן עצמו. לסרטון נדרש תמלול, לא רק קישור.",
    "الصق المحتوى نفسه. للفيديو نحتاج النص المفرغ، وليس الرابط فقط.",
  ],
  extract: [
    "Read material",
    "Прочитать материал",
    "קריאת החומר",
    "قراءة المادة",
  ],
  reviewSource: [
    "Check the extracted text",
    "Проверь извлечённый текст",
    "בדיקת הטקסט שחולץ",
    "راجع النص المستخرج",
  ],
  extractionHelp: [
    "Correct anything missing or misread before creating your study set.",
    "Исправь пропуски и ошибки до создания учебного набора.",
    "תקנו טקסט חסר או שגוי לפני יצירת ערכת הלימוד.",
    "صحح أي نص ناقص أو غير دقيق قبل إنشاء المجموعة.",
  ],
  create: [
    "Create study set",
    "Создать учебный набор",
    "יצירת ערכת לימוד",
    "إنشاء مجموعة دراسة",
  ],
  working: [
    "Putting the pieces together…",
    "Собираем всё вместе…",
    "מחברים את החלקים…",
    "نجمع الأجزاء معًا…",
  ],
  cancel: ["Cancel", "Отмена", "ביטול", "إلغاء"],
  back: ["Back", "Назад", "חזרה", "رجوع"],
  save: ["Save changes", "Сохранить", "שמירת שינויים", "حفظ التغييرات"],
  saved: [
    "Saved on this device",
    "Сохранено на устройстве",
    "נשמר במכשיר הזה",
    "محفوظ على هذا الجهاز",
  ],
  notes: ["Notes", "Заметки", "סיכומים", "ملاحظات"],
  cards: ["Flashcards", "Карточки", "כרטיסיות", "بطاقات"],
  questions: ["Practice questions", "Вопросы", "שאלות תרגול", "أسئلة تدريب"],
  generated: [
    "AI lesson · topic-based",
    "Урок ИИ · по теме",
    "שיעור AI · לפי נושא",
    "درس AI · حسب الموضوع",
  ],
  grounded: [
    "From your material",
    "Из твоего материала",
    "מתוך החומר שלך",
    "من مادتك",
  ],
  page: ["Page", "Страница", "עמוד", "صفحة"],
  flip: ["Reveal card", "Перевернуть", "הצגת כרטיסייה", "اكشف البطاقة"],
  warmup: ["Quick check", "Разминка", "בדיקה קצרה", "اختبار سريع"],
  learn: ["Make it click", "Разберёмся", "בואו נבין", "لنفهمها"],
  challenge: [
    "Try it on your own",
    "Попробуй самостоятельно",
    "נסו בעצמכם",
    "جرب بنفسك",
  ],
  teach: [
    "Teach it back",
    "Объясни своими словами",
    "הסבירו במילים שלכם",
    "اشرح بأسلوبك",
  ],
  teachPrompt: [
    "Explain the main idea to a friend. Include one example.",
    "Объясни главную мысль другу. Приведи пример.",
    "הסבירו את הרעיון לחבר והוסיפו דוגמה.",
    "اشرح الفكرة لصديق مع مثال.",
  ],
  feedbackNote: [
    "AI coaching feedback, not a formal grade.",
    "Обратная связь ИИ, не официальная оценка.",
    "משוב AI ללמידה, לא ציון רשמי.",
    "ملاحظات من AI وليست درجة رسمية.",
  ],
  answer: ["Your answer", "Твой ответ", "התשובה שלך", "إجابتك"],
  check: ["Check answer", "Проверить ответ", "בדיקת תשובה", "تحقق من الإجابة"],
  next: ["Next step", "Дальше", "השלב הבא", "الخطوة التالية"],
  hint: ["A little hint", "Подсказка", "רמז קטן", "تلميح صغير"],
  explain: ["Explain it", "Объясни", "הסבר", "اشرح لي"],
  guide: ["Guide me", "Направляй меня", "הנחיה", "وجهني"],
  checkWork: [
    "Check my work",
    "Проверь мою работу",
    "בדיקת הדרך שלי",
    "راجع عملي",
  ],
  tutor: [
    "Your study partner",
    "Твой помощник",
    "השותף ללמידה שלך",
    "شريكك في التعلم",
  ],
  ask: [
    "Ask about this step…",
    "Спроси об этом шаге…",
    "שאלו על השלב הזה…",
    "اسأل عن هذه الخطوة…",
  ],
  send: ["Send", "Отправить", "שליחה", "إرسال"],
  pause: ["Save & leave", "Сохранить и выйти", "שמירה ויציאה", "احفظ واخرج"],
  skip: ["Switch activity", "Сменить занятие", "החלפת פעילות", "غير النشاط"],
  recap: [
    "Look what you did.",
    "Посмотри, что получилось.",
    "תראו מה הצלחתם לעשות.",
    "انظر ماذا أنجزت.",
  ],
  improved: ["What improved", "Что получилось", "מה השתפר", "ما تحسن"],
  retry: [
    "Worth another try",
    "Стоит повторить",
    "כדאי לנסות שוב",
    "يستحق محاولة أخرى",
  ],
  review: [
    "Your next review",
    "Следующее повторение",
    "החזרה הבאה שלך",
    "مراجعتك التالية",
  ],
  reviewHelp: [
    "Come back tomorrow for a short recall check. Your review schedule adapts as you learn.",
    "Вернись завтра для короткого повторения. Расписание адаптируется к обучению.",
    "חזרו מחר לבדיקה קצרה. לוח החזרות מותאם להתקדמות.",
    "عد غدًا لمراجعة قصيرة. يتكيف جدول المراجعة مع تعلمك.",
  ],
  independent: [
    "Solved independently",
    "Решено самостоятельно",
    "נפתר באופן עצמאי",
    "حللتها باستقلالية",
  ],
  keepGoing: [
    "You made a start. Understanding grows with practice.",
    "Начало положено. Понимание растёт с практикой.",
    "עשיתם צעד ראשון. ההבנה גדלה עם התרגול.",
    "لقد بدأت. الفهم ينمو مع التدريب.",
  ],
  explore: [
    "More ways to make it stick",
    "Другие способы закрепить",
    "עוד דרכים לזכור",
    "طرق أخرى لترسيخ الفهم",
  ],
  exploreDesc: [
    "Change the activity, keep the curiosity.",
    "Меняй занятия, сохраняй любопытство.",
    "מחליפים פעילות, שומרים על הסקרנות.",
    "غير النشاط واحتفظ بالفضول.",
  ],
  games: ["Learning games", "Учебные игры", "משחקי למידה", "ألعاب تعليمية"],
  code: ["Code lab", "Лаборатория кода", "מעבדת קוד", "مختبر البرمجة"],
  debate: ["Debate arena", "Дебаты", "זירת דיון", "ساحة النقاش"],
  story: ["Story studio", "Студия историй", "סטודיו לסיפורים", "استوديو القصص"],
  slides: ["Presentations", "Презентации", "מצגות", "عروض تقديمية"],
  sql: ["SQL detective", "SQL-детектив", "בלש SQL", "محقق SQL"],
  courses: [
    "Explore courses",
    "Обзор курсов",
    "גילוי קורסים",
    "استكشف المقررات",
  ],
  legacy: [
    "Found older shared notes on this device. Import only notes that belong to you.",
    "Найдены старые общие заметки. Импортируй только свои.",
    "נמצאו סיכומים משותפים ישנים במכשיר. ייבאו רק סיכומים שלכם.",
    "وجدنا ملاحظات مشتركة قديمة. استورد ما يخصك فقط.",
  ],
  import: [
    "Import selected note",
    "Импортировать заметку",
    "ייבוא הסיכום הנבחר",
    "استورد الملاحظة",
  ],
  error: [
    "Something interrupted that step. Your input is still here. Please retry.",
    "Шаг прерван. Ввод сохранён. Попробуй ещё раз.",
    "השלב הופסק. הקלט עדיין כאן. נסו שוב.",
    "توقفت هذه الخطوة. مدخلاتك ما زالت هنا. حاول مجددًا.",
  ],
  storageError: [
    "Could not save on this device. Keep this tab open and retry saving before leaving.",
    "Не удалось сохранить. Не закрывай вкладку и повтори сохранение.",
    "השמירה נכשלה. השאירו את הלשונית פתוחה ונסו שוב לפני יציאה.",
    "تعذر الحفظ. أبق هذه الصفحة مفتوحة وأعد الحفظ قبل المغادرة.",
  ],
  invalidSource: [
    "Add readable content first. Links alone cannot be used as study material.",
    "Добавь читаемый текст. Одной ссылки недостаточно.",
    "הוסיפו תוכן קריא. קישור בלבד אינו חומר לימוד.",
    "أضف محتوى مقروءًا. الرابط وحده ليس مادة للدراسة.",
  ],
  retrySave: [
    "Retry saving",
    "Повторить сохранение",
    "ניסיון שמירה נוסף",
    "أعد الحفظ",
  ],
  correct: ["You’ve got it!", "Верно!", "הצלחתם!", "أحسنت!"],
  notYet: [
    "Let’s untangle this.",
    "Давай разберёмся.",
    "בואו נפתור את זה.",
    "لنفهم هذا معًا.",
  ],
  finish: ["See my recap", "Итоги", "הסיכום שלי", "اعرض ملخصي"],
  duration: [
    "Session length",
    "Длительность занятия",
    "משך הסבב",
    "مدة الجلسة",
  ],
  readFirst: [
    "Read, then try a new example.",
    "Прочитай и попробуй новый пример.",
    "קראו ואז נסו דוגמה חדשה.",
    "اقرأ ثم جرب مثالًا جديدًا.",
  ],
  activity: ["Activity", "Задание", "פעילות", "نشاط"],
  reviewPriority: [
    "A fresh look at a skill you’ve practiced",
    "Новый взгляд на знакомый навык",
    "מבט חדש על מיומנות שכבר תרגלתם",
    "نظرة جديدة على مهارة تدربت عليها",
  ],
  noQuestions: [
    "Create practice from these notes",
    "Создать практику по заметкам",
    "יצירת תרגול מהסיכומים",
    "أنشئ تدريبًا من الملاحظات",
  ],
  celebrations: [
    "Celebrate small wins",
    "Отмечать маленькие победы",
    "לחגוג הצלחות קטנות",
    "احتفل بالإنجازات الصغيرة",
  ],
  account: ["Account", "Аккаунт", "חשבון", "الحساب"],
  evidence: [
    "Small steps, real understanding.",
    "Маленькие шаги, настоящее понимание.",
    "צעדים קטנים, הבנה אמיתית.",
    "خطوات صغيرة، فهم حقيقي.",
  ],
  evidenceHelp: [
    "Your progress grows through independent recall across different days.",
    "Прогресс растёт благодаря самостоятельному повторению в разные дни.",
    "ההתקדמות גדלה דרך שליפה עצמאית בימים שונים.",
    "ينمو تقدمك عبر الاسترجاع المستقل في أيام مختلفة.",
  ],
  skills: [
    "Skills you’re building",
    "Навыки, которые ты развиваешь",
    "המיומנויות שאתם מפתחים",
    "المهارات التي تبنيها",
  ],
  completed: [
    "Sprints completed",
    "Завершённые спринты",
    "סבבים שהושלמו",
    "الجولات المكتملة",
  ],
  due: ["Ready for review", "Пора повторить", "מוכנים לחזרה", "جاهزة للمراجعة"],
} satisfies Record<string, [string, string, string, string]>;
export type StudyCopy = Record<keyof typeof rows, string>;
export function studyCopy(lang: Language): StudyCopy {
  const index = { en: 0, ru: 1, he: 2, ar: 3 }[lang];
  return Object.fromEntries(
    Object.entries(rows).map(([key, values]) => [key, values[index]]),
  ) as StudyCopy;
}
